---
- hosts: all
  user: vagrant
  become: yes
  tasks:

  - name: Install packages
    apt:
      name: ['ca-certificates', 'software-properties-common', 'apt-transport-https', 'python3.5', 'python3-pip', 'python3.5-venv', 'git', 'gunicorn']

  - name: Clone the Repo
    git: clone=yes repo=https://github.com/rlennon/Doodle.git dest=/home/vagrant/Doodle

  - name: Create a virtual environment
    command: python3.5 -m venv /home/vagrant/Doodle/env creates="/home/vagrant/Doodle/env"

  - name: install requirements
    pip:
      requirements: /home/vagrant/Doodle/src/POC/infrastructure/requirements.txt
      virtualenv: /home/vagrant/Doodle/env

- hosts: web.internal.tld
  user: vagrant
  become: yes
  tasks:

  - name: Copy systemd script
    template: src=./systemd_config_web dest=/lib/systemd/system/doodleweb.service

  - name: Start API
    service: name=doodleweb state=started enabled=yes

- hosts: api.internal.tld
  user: vagrant
  become: yes
  tasks:

  - name: Add GPG key
    apt_key:
      id: "7F0CEB10"
      keyserver: "keyserver.ubuntu.com"

  - name: Configure APT repository
    apt_repository:
      repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
      update_cache: true

  - name: Install packages
    apt:
      name: mongodb

  - name: Copy systemd script
    template: src=./systemd_config_api dest=/lib/systemd/system/doodleapi.service

  - name: Start API
    service: name=doodleapi state=started enabled=yes
